name: qsr
channels:
  - pytorch
  - defaults
dependencies:
  - tqdm
  - numpy
  - pillow
  - pytorch
  - torchvision
  - scipy
  - h5py
  - termcolor
  - python=3.6
  - munch
  - gitpython
  - tensorboard
  - python-dateutil
