entity_names = [
    "slightly smiling face",
    "nerd face",
    "smiling face with halo",
    "expressionless face",
    "flushed face",
    "face with tears of joy",
    "neutral face",
    "smiling face with heart-eyes",
    "face with medical mask",
    "loudly crying face",
    "hugging face",
    "smiling face with smiling eyes",
    "squinting face with tongue",
    "face with steam from nose",
    "dog face",
    "cat face",
    "face screaming in fear",
    "pouting face",
    "pig face",
    "rabbit face",
    "tiger face",
    "monkey face",
    "cow face",
    "tired face",
    "mouse face",
    "dragon face",
    "face with tongue",
    "sun with face",
    "worried face",
    "dizzy face",
    "face with open mouth",
    "fearful face",
]

excluded_entity_names_18 = [
    "hugging face",
    "fearful face",
    "face with steam from nose",
    "face with tongue",
    "nerd face",
    "expressionless face",
    "dragon face",
    "flushed face",
    "cow face",
    "smiling face with heart-eyes",
    "sun with face",
    "pig face",
    "pouting face",
    "smiling face with halo",
    "slightly smiling face",
    "worried face",
    "neutral face",
    "loudly crying face",
]

excluded_entity_names_1left = [
    "slightly smiling face",
    # "nerd face",
    "smiling face with halo",
    "expressionless face",
    "flushed face",
    "face with tears of joy",
    "neutral face",
    "smiling face with heart-eyes",
    "face with medical mask",
    "loudly crying face",
    "hugging face",
    "smiling face with smiling eyes",
    "squinting face with tongue",
    "face with steam from nose",
    "dog face",
    "cat face",
    "face screaming in fear",
    "pouting face",
    "pig face",
    "rabbit face",
    "tiger face",
    "monkey face",
    "cow face",
    "tired face",
    "mouse face",
    "dragon face",
    "face with tongue",
    "sun with face",
    "worried face",
    "dizzy face",
    "face with open mouth",
    "fearful face",
]

relation_names_abs_intri = ["left_of", "right_of", "above", "below"]
excluded_relation_names_all4_abs_intri = ["left_of", "right_of", "above", "below"]
excluded_relation_names_above_below_abs_intri = ["above", "below"]


relation_names_rel = ["left_of", "right_of", "in_front_of", "behind"]
excluded_relation_names_all4_rel = ["left_of", "right_of", "in_front_of", "behind"]
excluded_relation_names_front_behind_rel = ["in_front_of", "behind"]